// <auto-generated />
using System;
using GOSDataModel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GOSDataModel.Migrations
{
    [DbContext(typeof(GOSContext))]
    [Migration("20190508032629_CreateIdentitySchema")]
    partial class CreateIdentitySchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GOSDataModel.Models.Color", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("ColorName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("GOSDataModel.Models.Order", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("Cash");

                    b.Property<int?>("CustomerId");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Status");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("GOSDataModel.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("OrderId");

                    b.Property<int?>("ProductId");

                    b.Property<int?>("Quantity");

                    b.HasKey("Id");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("GOSDataModel.Models.Product", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("CategoryId");

                    b.Property<string>("ColorId");

                    b.Property<DateTime?>("Date");

                    b.Property<string>("Description");

                    b.Property<int?>("Discount");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Price")
                        .HasMaxLength(50);

                    b.Property<string>("ProductName");

                    b.Property<string>("SizeId");

                    b.Property<int?>("Status");

                    b.Property<int?>("SupplyId");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("GOSDataModel.Models.Size", b =>
                {
                    b.Property<int>("SizeId");

                    b.Property<string>("Description")
                        .HasMaxLength(100);

                    b.Property<string>("SizeName")
                        .HasMaxLength(50);

                    b.HasKey("SizeId");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("GOSDataModel.Models.User", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Email");

                    b.Property<string>("PassWord")
                        .HasMaxLength(50);

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
